package common

const JWTSECRETSALT = "LUTASAM"

const (
	STATUSOKCODE    = 200
	CLIENTERRORCODE = 404
	SERVERERRORCODE = 500
)

const (
	STATUSOKMSG    = "OK"
	CLIENTERRORMSG = "404 NOT FOUND"
	SERVERERRORMSG = "500 SERVER ERROR"
)
