package common

const ISSUER = "LUTASAM"
const JWTSECRETSALT = "LUTASAM"
const PASSWORDSALT = "astaxie12798akljzmknm.ahkjkljl;k"
const EXPIRETIME = 86400000

const (
	STATUSOKCODE    = 200
	CLIENTERRORCODE = 404
	SERVERERRORCODE = 500
)

const (
	STATUSOKMSG    = "OK"
	CLIENTERRORMSG = "404 NOT FOUND"
	SERVERERRORMSG = "500 SERVER ERROR"
)
