# server config
server:
  port: 8080
# mysql config
mysql:
  dsn: root:root@/test?charset=utf8&parseTime=True&loc=Local
# redis config
redis:
  address:
# log config
log:
  filepath: log/log.log